In [4]:
#Implementing the Multiple Linear Regression Algorithm using python and numpy library

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [25]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
print(X_train)
print(y_train)
X_train.shape

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


(3, 4)

In [26]:
def compute_gradient_descent_summation_part(X,y,w,b):
    m,n = X.shape
    #m number of examples and n is number of features
    w_temp = np.zeros((n,)) #weights
    b_temp = 0 #bias
    for i in range(m):
        err = (np.dot(X[i],w)+b) - y[i]
        for j in range(n):
            w_temp[j] = w_temp[j] + err* X[i,j]
        b_temp += err
    w_temp = w_temp/m
    b_temp = b_temp/m
    
    return w_temp,b_temp


In [27]:
def gradient_descent(X,y,w,b,iterations,alpha):
    for i in range(iterations):
        w_temp,b_temp = compute_gradient_descent_summation_part(X,y,w,b)
        w = w - alpha * w_temp
        b = b - alpha * b_temp
    return w,b
    
    

In [40]:
w_init = np.zeros(X_train.shape[1])
b_init = 0.
w_final,b_final = gradient_descent(X_train,y_train,w_init,b_init,1000,5.0e-7)

In [41]:
w_final,b_final

(array([ 0.20396569,  0.00374919, -0.0112487 , -0.0658614 ]),
 -0.0022354075309325345)

In [43]:
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
